package TaskAppEnums;

public enum Endpoint {
    GET_TASK,
    GET_EPIC,
    GET_SUBTASK,
    GET_TASKS,
    GET_EPICS,
    GET_SUBTASKS,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED,
    POST_UPDATE_TASK,
    POST_UPDATE_EPIC,
    POST_UPDATE_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    DELETE_TASKS,
    DELETE_EPICS,
    DELETE_SUBTASKS,
    UNKNOWN
}